services:
  postgres:
    container_name: timetable-postgres
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.pg
    ports:
      - 5432:5432

volumes:
  pgdata: