spring:
  application:
    name: timetable-backend
  datasource:
    postgre:
      driver: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/timetable_db
      username: timetable
      password: password
